name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-20.04
    if: github.repository == 'freeCodeCamp/devdocs'
    steps:
    - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@f60ef1e8084a2e64569f928c3f1cfac6c7e12ad7 # v1.137.2
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@5ef17ff17a3fb8e9ad822ae6a61648a3ef9e0c3d # v3.12.13
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "devdocs"
        heroku_email: "team@freecodecamp.com"
        dontuseforce: true # --force should never be necessary
        dontautocreate: true # The app exists, it should not be created
