name: Generate documentation versions report
on:
  schedule:
    - cron: '17 4 1 * *'

jobs:
  report:
    runs-on: ubuntu-20.04
    if: github.repository == 'freeCodeCamp/devdocs'
    steps:
    - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2.4.2
    - name: Set up Ruby
      uses: ruby/setup-ruby@a1396b7d70b0d60cdf1d24584544a1f7024695b0 # tag=v1.115.1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Generate report
      run: bundle exec thor updates:check --github-token ${{ secrets.DEVDOCS_BOT_PAT }} --upload
