name: Generate documentation versions report
on:
  schedule:
    - cron: '17 4 1 * *'

jobs:
  report:
    runs-on: ubuntu-20.04
    if: github.repository == 'freeCodeCamp/devdocs'
    steps:
    - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # tag=v2.5.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@84dd2abab6ed441bd503503b9adb1f52680f7349 # v1.122.0
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Generate report
      run: bundle exec thor updates:check --github-token ${{ secrets.DEVDOCS_BOT_PAT }} --upload
