name: Ruby tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2.4.2
    - name: Set up Ruby
      uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # tag=v1.115.3
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake
